### ISSUE TITLE
Landing is too soft

### ISSUE THREAD

**Issue by nevercast** [allista/ThrottleControlledAvionics#25]
The surface landing mode descends at -1m/s, which wastes a lot of fuel to gravity. Can I increase the rate that I descend at but still land safely within a 6m/s margin just before I hit the ground? I have a 10 TWR so there is no harm in free falling and doing a suicide burn.

**Comment by allista** [comment]
No, it's not configurable. But the -1m/s is only used at a final stage, when the ship is already near the ground. Before that the Altitude Control is used which takes into account TWR and many other parameters to set the vertical speed.
Could you describe your situation in more detail? Planet/moon, engines' type, etc...

**Comment by nevercast** [comment]
Yes certainly,

I'm attempting to land on Duna, the engine is the Sky Crane from USI Kolonization. I've over 3k delta v, so plenty to deorbit from low Duna orbit and land.

Here is the vessel and initial deorbit trajectory.

![20161028152354_1](https://cloud.githubusercontent.com/assets/834342/19792225/d7911a0a-9d24-11e6-82e7-af20e1d64e83.jpg)
![20161028152436_1](https://cloud.githubusercontent.com/assets/834342/19792229/d9314c4a-9d24-11e6-8e53-0ef5a457744e.jpg)
![20161028152505_1](https://cloud.githubusercontent.com/assets/834342/19792232/dabf0368-9d24-11e6-93b6-dc0710f95320.jpg)

During Coasting and Final Decent the thrust is quite constant
https://youtu.be/ml58engIRTw?t=205

Then a lot of dV is used failing to scan the surface, I'm not sure if low slope is out of range of the radar but it fails to find somewhere to land, https://youtu.be/ml58engIRTw?t=314

The parachutes and air brakes are not used during decent either and were provided to spare Delta V.

If you've any suggestions, I'll try other approaches. 
Regards, NeverCast.

**Comment by allista** [comment]
Thank you for such a thorough explanation! It's rare and pleasant!
And I see your point.
I'll try to think of some improvements to the landing and scanning algorithms.

What happens here is:

1. The ~constant low thrust is an attempt to keep the landing site within 100m of the target against the drag forces. I'll try to make it more flexible, but without it the landing site moves quite quickly and I fear more fuel will be needed to correct this at a later point.
2. The surface scanner scans a wide patch of the ground beneath the ship. That's why it tries to climb higher when it finds no flat-enough surfaces -- to cover more ground. What I could do here is to add a switch to disable the search completely (just land a the target, no matter what); or I could try to do a preliminary scan during final deceleration to have a rough map of terrain beforehand. This, however, is not a simple thing to do, considering the speeds involved, and the fact that the terrain is loaded recursively depending on the distance to the ship (so no real high-altitude high-precision scans).
3. The chutes and brakes are not used, because they drastically decrease maneuverability (to the point of complete loss of control), which is not the thing you what when you're trying to do a precise powered landing. Also, to program the correct usage of different chutes I need to closely simulate an atmospheric trajectory of an object with variable drag. Which is computationally intensive.
    1. But, they are used at the deceleration/final deceleration if there's not enough fuel for landing.

As for suggestions: you can terminate the landing program (with Stop button) when the scanning stage starts, and land manually using Altitude Control.

**Comment by allista** [comment]
In v3.3.0 a landing ship scans the surface just before the main deceleration burn and corrects the target if necessary. This should partly resolve the issue as the course adjustment during deceleration from high altitude costs much less than the active searching later that ate all your fuel.

This, of course, is not all I'm planning to do about this issue, but that's a start.

**Comment by nevercast** [comment]
Thanks @allista, sounds good! I'll update and give that a test.

**Comment by allista** [comment]
I believe I've done everything I could currently come up with to alleviate this problem. This includes the explicit options to use brakes and/or chutes during deceleration stages and the option to disable near-surface search pattern (called "Land ASAP").

The first two options don't work as immediate order, but rather "allow" the autopilot to use corresponding actions when it sees appropriate (which is not an easy thing to calculate). So don't expect to conserve much fuel: the precision of the landing is still a priority.

All this is available since v3.3.1.

I'm leaving the issue open until you will have time to test it. Then you can close it if you deem it resolved.

**Comment by nevercast** [comment]
Thanks @allista. I'm without internet at home currently but once that's connected I'll update and test.

**Comment by fx-pain** [comment]
Excellent mod. Landing script almost perfect.
But I noticed one more problem with landing on Duna. Looks like landing script didn't take atmosphere into account on decceleration. After decceleration burn it constantly burning down to correct landing spot due to drag losses. Mechjeb handling this part better, stretching decceleration burn in time. dV difference between TCA and MJ in my case was 400m/s (MJ-900m/s). Landing sequence was almost identical in both cases, from deorbit to touchdown, with parachutes opened on near zero horizontal speed. Accuracy: MJ - 30m from target, TCA - 10m.

**Comment by allista** [comment]
In the upcoming TCA-3.5 this will be handled with proper atmospheric simulation. I'm not sure if it will work as good with FAR as with stock aerodynamics, but it's sure better than what we have now.
